debug: true
logging:
  version: 1
  loggers:
    ess:
      level: DEBUG
      qualname: ess
      handlers:
        - console
  formatters:
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
      stream: ext://sys.stdout
  root:
    level: DEBUG
