version: '2'
services:
  postgresql:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=devPWD
      - POSTGRES_USER=dev
      - POSTGRES_DB=ess

volumes:
  postgresql:
    driver: local
